<a href="https://colab.research.google.com/github/woodskd24/MentalHealthinUSA/blob/main/MentalHealthPredictionClean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#Data From https://data.world/vizzup/mental-health-depression-disorder-data/workspace/file?filename=Mental+health+Depression+disorder+Data.xlsx
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns

In [15]:
MH = pd.read_csv('/content/drive/MyDrive/MentalHealthData.csv')
MH

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,0.160560,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,0.155670,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,Zimbabwe,ZWE,2014,0.155993,0.608610,0.118073,3.093964,0.768914,3.140290,1.515470
6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.119470,3.098687,0.771802,3.155710,1.514751
6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [16]:
USM = MH[MH['Entity'] == "United States"]
USM

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
6076,United States,USA,1990,0.340897,0.653706,0.468676,6.576884,2.367794,4.677591,2.173751
6077,United States,USA,1991,0.338913,0.653953,0.473575,6.553351,2.345466,4.660871,2.139292
6078,United States,USA,1992,0.337343,0.654205,0.478610,6.536143,2.339515,4.651949,2.107931
6079,United States,USA,1993,0.336207,0.654431,0.483539,6.525536,2.347095,4.648701,2.080669
6080,United States,USA,1994,0.335536,0.654620,0.488235,6.522278,2.365738,4.649294,2.058632
6081,United States,USA,1995,0.335363,0.654721,0.492368,6.526489,2.392582,4.650869,2.042931
6082,United States,USA,1996,0.335806,0.654749,0.496752,6.578023,2.456048,4.662902,2.033987
6083,United States,USA,1997,0.336797,0.654720,0.501560,6.688847,2.564591,4.689154,2.030590
6084,United States,USA,1998,0.338085,0.654658,0.506483,6.818473,2.688823,4.720716,2.031176
6085,United States,USA,1999,0.339410,0.654564,0.511072,6.926351,2.800595,4.749991,2.034175
6086,United States,USA,2000,0.340512,0.654443,0.514863,6.971563,2.869426,4.766992,2.038026
6087,United States,USA,2001,0.341186,0.654371,0.518306,6.971995,2.905605,4.774031,2.043577
6088,United States,USA,2002,0.341483,0.654349,0.522170,6.971891,2.936109,4.778244,2.051480
6089,United States,USA,2003,0.341535,0.654343,0.526130,6.970935,2.962640,4.781680,2.059815
6090,United States,USA,2004,0.341472,0.654313,0.529332,6.968875,2.983414,4.785232,2.066706
6091,United States,USA,2005,0.341427,0.654228,0.531157,6.965249,2.998771,4.791258,2.070251
6092,United States,USA,2006,0.341031,0.654080,0.532178,6.937038,3.000826,4.793213,2.063498
6093,United States,USA,2007,0.340069,0.653896,0.533067,6.875454,2.989141,4.786623,2.045624
6094,United States,USA,2008,0.338901,0.653691,0.533768,6.801899,2.974336,4.776402,2.023935
6095,United States,USA,2009,0.337887,0.653468,0.534175,6.737790,2.966808,4.765950,2.005749
6096,United States,USA,2010,0.337390,0.653247,0.534076,6.704455,2.977144,4.761551,1.998437
6097,United States,USA,2011,0.337190,0.653008,0.533199,6.693384,3.007049,4.762322,1.999569
6098,United States,USA,2012,0.336852,0.652748,0.531514,6.682107,3.052340,4.765481,2.001951
6099,United States,USA,2013,0.336404,0.652479,0.528946,6.671047,3.110712,4.772422,2.005814
6100,United States,USA,2014,0.335860,0.652195,0.525990,6.660473,3.181115,4.782222,2.011345
6101,United States,USA,2015,0.335243,0.651890,0.522109,6.650662,3.262674,4.795954,2.018738
6102,United States,USA,2016,0.334578,0.651569,0.517728,6.642099,3.353142,4.813114,2.028263
6103,United States,USA,2017,0.333890,0.651236,0.512844,6.635055,3.452476,4.835610,2.040087

In [17]:
USM.describe()

,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
mean,2003.500000,0.338117,0.653710,0.513658,6.741584,2.844713,4.744655,2.046643
std,8.225975,0.002424,0.001028,0.020454,0.165191,0.327117,0.057619,0.040801
min,1990.000000,0.333890,0.651236,0.468676,6.522278,2.339515,4.648701,1.998437
25%,1996.750000,0.336120,0.653187,0.500358,6.620797,2.537456,4.686263,2.022636
50%,2003.500000,0.337639,0.654143,0.520208,6.691116,2.964724,4.766471,2.039057
75%,2010.250000,0.340608,0.654434,0.531246,6.929023,3.002382,4.782974,2.060735
max,2017.000000,0.341535,0.654749,0.534175,6.971995,3.452476,4.835610,2.173751

In [18]:
USM.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 6076 to 6103
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Entity                     28 non-null     object
 1   Code                       28 non-null     object
 2   Year                       28 non-null     int64
 3   Schizophrenia (%)          28 non-null     float64
 4   Bipolar disorder (%)       28 non-null     float64
 5   Eating disorders (%)       28 non-null     float64
 6   Anxiety disorders (%)      28 non-null     float64
 7   Drug use disorders (%)     28 non-null     float64
 8   Depression (%)             28 non-null     float64
 9   Alcohol use disorders (%)  28 non-null     float64
dtypes: float64(7), int64(1), object(2)
memory usage: 2.4+ KB

In [19]:
USA = USM.drop(columns = "Code")
df = USA.drop(columns = "Entity")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 6076 to 6103
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       28 non-null     int64
 1   Schizophrenia (%)          28 non-null     float64
 2   Bipolar disorder (%)       28 non-null     float64
 3   Eating disorders (%)       28 non-null     float64
 4   Anxiety disorders (%)      28 non-null     float64
 5   Drug use disorders (%)     28 non-null     float64
 6   Depression (%)             28 non-null     float64
 7   Alcohol use disorders (%)  28 non-null     float64
dtypes: float64(7), int64(1)
memory usage: 2.0 KB

In [21]:
df.isnull().sum()

Year                         0
Schizophrenia (%)            0
Bipolar disorder (%)         0
Eating disorders (%)         0
Anxiety disorders (%)        0
Drug use disorders (%)       0
Depression (%)               0
Alcohol use disorders (%)    0
dtype: int64

In [22]:
df.shape

(28, 8)

In [23]:
df.to_csv(r'/content/drive/MyDrive/MHPred.csv', index = False)